vc_chain/urls.py
from django.conf.urls import url
from django.contrib import admin
from vc_chain import views, settings
from django.conf.urls.static import static

app_name = 'vc_chain'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.indexRedirect),
    url(r'^index/$', views.indexView, name="index"),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^signout/$', views.signout, name="signout"),
    url(r'^dashboard/$', views.dashboardRedirect),
    url(r'^user/(?P<username>[\w_]{3,50})/dashboard$', views.dashboardView, name="dashboard"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/add$', views.addProjectView, name="add-project"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/edit/(?P<filename>[-\w_.]{3,50})/$', views.codeEditView, name="code-edit"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/view/(?P<filename>[-\w_.]{3,50})/$', views.codeView, name="code"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/commits/(?P<commitid>\w{1,50})/$', views.commitView, name="commit-diff"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/commits/$', views.commitsListView, name="commits-view"),
    url(r'^user/(?P<username>[\w_]{3,50})/edit/$', views.editProfileView, name="edit-profile"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>\w{3,50}|_.)/explore/$', views.projectExplorerView, name="project-explorer"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/explore/$', views.projectExplorerView, name="project-explorer"),

    url(r'^user/(?P<username>[\w_]{3,50})/projects/$', views.projectsListView, name='projects-list'),
    url(r'^user/(?P<username>[\w_]{3,50})/stars/$', views.starProjectsListView, name='stars-list'),
    url(r'^user/(?P<username>[\w_]{3,50})/forks/$', views.forkProjectsListView, name='forks-list'),

    url(r'^user/(?P<username>[\w_]{3,50})/followers/$', views.followersView, name="followers-list"),
    url(r'^user/(?P<username>[\w_]{3,50})/following/$', views.followingsView, name="following-list"),

    url(r'^user/(?P<username>[\w_]{3,50})/profile-edit/$', views.editProfile, name="edit-profile-request"),
    url(r'^user/(?P<username>[\w_]{3,50})/add-project/$', views.addProject, name="add-project-request"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/edit-file-request$', views.codeEditFile, name="code-edit-request"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/(?P<branchname>[-\w_]{3,50})/delete/(?P<filename>[-\w_.]{3,50})/$', views.codeDeleteFile, name="delete-file-request"),

    url(r'^user/(?P<username>[\w_]{3,50})/follow/(?P<following>[\w_]{3,50})$', views.followUser, name="follow"),
    url(r'^user/(?P<username>[\w_]{3,50})/unfollow/(?P<following>[\w_]{3,50})$', views.unfollowUser, name="unfollow"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/star/(?P<starrer>[\w_]{3,50})$', views.starProject, name="project-star"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/unstar/(?P<starrer>[\w_]{3,50})$', views.unstarProject, name="project-unstar"),
    url(r'^user/(?P<username>[\w_]{3,50})/projects/(?P<projectname>[-\w_]{3,50})/fork/(?P<forker>[\w_]{3,50})$', views.forkProject, name="project-fork"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vc_chain/models.py
from django.db import models
import uuid
import os


class User(models.Model):

    def get_upload_to(instance, filename):
        upload_to = 'user_avatars'
        ext = filename.split('.')[-1]
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            filename = '{}.{}'.format(uuid.uuid4().hex, ext)
        return upload_to + '/' + filename

    username = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    avatar = models.ImageField(upload_to=get_upload_to, default='user_avatars/default-avatar.jpg', blank=False, null=False)

    def __str__(self):
        return self.username


class Project(models.Model):
    name = models.CharField(max_length=30)
    branch = models.CharField(max_length=20)
    author = models.ForeignKey(User)
    forked_from = models.OneToOneField('Project', null=True, blank=True)
    description = models.CharField(max_length=256)
    is_main_branch = models.BooleanField()

    def __str__(self):
        return self.name + "/" + self.branch


class Star(models.Model):
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user) + "-" + str(self.project)


class Fork(models.Model):
    forked_project = models.ForeignKey(Project, related_name="project_after_fork")
    original_project = models.ForeignKey(Project, related_name="original_project")
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.forked_project) + "-" + str(self.original_project)


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name="person_following")
    followed = models.ForeignKey(User, related_name="person_followed")
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.follower) + "-" + str(self.followed)


class Commit(models.Model):
    commit_id = models.AutoField(primary_key=True)
    project = models.ForeignKey(Project)
    message = models.CharField(max_length=1024)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project) + "-" + str(self.commit_id)


class File(models.Model):
    commit = models.ForeignKey(Commit)
    name = models.CharField(max_length=50)
    size = models.CharField(max_length=10)
    code = models.TextField()
    previous_file = models.ForeignKey('File', null=True, blank=True)

    def __str__(self):
        return str(self.commit) + "-" + self.name

vc_chain/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from vc_chain import data_handler
from vc_chain import models


def indexView(request):
    return render(request, 'index.html')


def indexRedirect(request):
    if request.user.is_authenticated():
        return dashboardRedirect(request)
    else:
        return render(request, 'index.html')


def signin(request):
    username = request.POST['username']
    password = request.POST['password']
    auth_user = authenticate(request, username=username, password=password)
    if auth_user is not None:
        login(request, auth_user)
        return dashboardRedirect(request)
    else:
        return indexRedirect(request)


def signup(request):
    username = request.POST['username']
    password = request.POST['password']
    fname = request.POST['first_name']
    email = request.POST['email']
    User.objects.create_user(username=username, email=email, password=password, first_name=fname).save()
    auth_user = authenticate(request, username=username, password=password)
    if auth_user is not None:
        models.User(username=username, name=fname, email=email).save()
        login(request, auth_user)
        return dashboardRedirect(request)
    else:
        return indexRedirect(request)


def signout(request):
    logout(request)
    return redirect("/")


@login_required
def dashboardRedirect(request):
    return redirect('/user/' + request.user.username + "/dashboard")


def dashboardView(request, username):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "timeline": data_handler.getTimelineData(username),
        "commit_stat": data_handler.getCommitStatsData(username),
    }
    return render(request, 'dashboard.html', data)


@login_required
def addProjectView(request, username):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
    }
    return render(request, 'add-project.html', data)


@login_required
def codeEditView(request, username, projectname, branchname, filename):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "file": data_handler.getFileCodeData(username, projectname, branchname, filename),
    }
    return render(request, 'code-edit.html', data)


def codeView(request, username, projectname, branchname, filename):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "file": data_handler.getFileCodeData(username, projectname, branchname, filename),
    }
    return render(request, 'code-view.html', data)


def commitView(request, username, projectname, branchname, commitid):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "commit_diff": data_handler.getCommitDiffData(username, projectname, branchname, commitid),
    }
    return render(request, 'commit-view.html', data)


def commitsListView(request, username, projectname, branchname):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "commits": data_handler.getCommitListData(username, projectname, branchname),
    }
    return render(request, 'commits.html', data)


@login_required
def editProfileView(request, username):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
    }
    return render(request, 'edit-profile.html', data)


def followersView(request, username):
    data = {
        "type": "Followers",
        "user": data_handler.getUserData(username, request.user.username),
        "people": data_handler.getFollowerData(username),
    }
    return render(request, 'people.html', data)


def followingsView(request, username):
    data = {
        "type": "Following",
        "user": data_handler.getUserData(username, request.user.username),
        "people": data_handler.getFollowingData(username),
    }
    return render(request, 'people.html', data)


def projectExplorerView(request, username, projectname, branchname=None):
    data = {
        "user": data_handler.getUserData(username, request.user.username),
        "project": data_handler.getProjectExplorerData(username, projectname, branchname, request.user.username),
    }
    return render(request, 'project-explore.html', data)


def projectsListView(request, username):
    data = {
        "type": "Projects",
        "user": data_handler.getUserData(username, request.user.username),
        "projects": data_handler.getProjectListData(username),
    }
    return render(request, 'projects.html', data)


def starProjectsListView(request, username):
    data = {
        "type": "Stars",
        "user": data_handler.getUserData(username, request.user.username),
        "projects": data_handler.getStarProjectListData(username),
    }
    return render(request, 'projects.html', data)


def forkProjectsListView(request, username):
    data = {
        "type": "Forks",
        "user": data_handler.getUserData(username, request.user.username),
        "projects": data_handler.getProjectListData(username, just_fork=True),
    }
    return render(request, 'projects.html', data)


@login_required
def addProject(request, username):
    project_name = request.POST["projectnameinput"]
    branch_name = request.POST["branchnameinput"]
    project_descr = request.POST['descriptioninput']
    commit_msg = request.POST['commitmessageinput']
    files = request.FILES.getlist('files[]')

    data_handler.addProject(username, project_name, branch_name, project_descr, commit_msg, files)

    return redirect('/user/' + request.user.username + "/projects")


@login_required
def codeEditFile(request, username, projectname, branchname):
    oldfilename = request.POST['editoroldfilename']
    filename = request.POST['editorfilename']
    code = request.POST['editorcode']
    commit_msg = request.POST['editorcommit']

    data_handler.editFile(username, projectname, branchname, oldfilename, filename, code, commit_msg)

    return codeView(request, username, projectname, branchname, filename)


@login_required
def codeDeleteFile(request, username, projectname, branchname, filename):
    commit_msg = request.POST['editorcommit']

    data_handler.deleteFile(username, projectname, branchname, filename, commit_msg)

    return codeView(request, username, projectname, branchname, filename)


@login_required
def editProfile(request, username):
    new_name = request.POST['profileName']
    new_username = request.POST['profileUsername']
    new_email = request.POST['profileEmail']
    new_password = request.POST['profilePassword']
    if 'profileImageFile' in request.POST:
        new_image = request.POST['profileImageFile']
    elif 'profileImageFile' in request.FILES:
        new_image = request.FILES['profileImageFile']
    else:
        new_image = ''

    data_handler.editProfile(username, new_username, new_name, new_email, new_image, new_password)

    return redirect('/')


@login_required
def followUser(request, username, following):
    data_handler.addFollow(username, following)
    return followingsView(request, username)


@login_required
def unfollowUser(request, username, following):
    data_handler.removeFollow(username, following)
    return followingsView(request, username)


@login_required
def starProject(request, username, projectname, starrer):
    data_handler.addStar(username, projectname, starrer)
    return projectExplorerView(request, username, projectname)


@login_required
def unstarProject(request, username, projectname, starrer):
    data_handler.removeStar(username, projectname, starrer)
    return projectExplorerView(request, username, projectname)


@login_required
def forkProject(request, username, projectname, forker):
    data_handler.makeFork(username, projectname, forker)
    return projectsListView(request, username)

vc_chain/templates/add-project.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
      <title>VC-chain</title>
      <link href="{% static 'plugins/jquery.filer/css/jquery.filer.css' %}" rel="stylesheet" />
      <link href="{% static 'plugins/jquery.filer/css/themes/jquery.filer-dragdropbox-theme.css' %}" rel="stylesheet" />
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
   </head>
   <body class="fixed-left">
      <div id="wrapper">
      <div class="topbar">
         <div class="topbar-left">
            <a href="{% url 'index' %}" class="logo">
            <i class="fa fa-link"></i>
            <span>VC-chain</span>
            </a>
         </div>
         <nav class="navbar-custom">
            {% include "user_dropdown.html" %}
            <ul class="list-inline menu-left mb-0">
               <li class="float-left">
                  <button class="button-menu-mobile open-left waves-light waves-effect">
                  <i class="zmdi zmdi-menu"></i>
                  </button>
               </li>
            </ul>
         </nav>
      </div>
      <div class="left side-menu">
      <div class="sidebar-inner slimscrollleft">
        {% include "sidebar_menu.html" %}
         <div class="content-page">
            <div class="content">
               <div class="container-fluid">
                  <div class="row">
                     <div class="col-xl-12">
                        <div class="page-title-box">
                           <h4 class="page-title float-left">Add Project</h4>
                           <ol class="breadcrumb float-right">
                              <li class="breadcrumb-item"><a href="{% url 'index' %}">VC-Chain</a></li>
                              <li class="breadcrumb-item"><a href="{% url 'dashboard' user.username %}">{{ user.username }}</a></li>
                              <li class="breadcrumb-item"><a href="{% url 'projects-list' user.username %}">Projects</a></li>
                              <li class="breadcrumb-item active">Add</li>
                           </ol>
                           <div class="clearfix"></div>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-12">
                        <div class="card-box">
                           <form role="form" method="post" action="{% url 'add-project-request' user.username %}" enctype="multipart/form-data" data-parsley-validate>
                              {% csrf_token %}
                              <div class="row">
                                 <div class="col-sm-12 col-xs-12 col-md-6">
                                    <div class="form-group">
                                       <label for="projectnameinput">Project name</label><span class="text-danger">*</span>
                                       <input type="text" class="form-control" name="projectnameinput" parsley-trigger="change" required="required" placeholder="Enter project name"  data-parsley-pattern="^[-\w_]{3,50}$">
                                       <small class="text-muted">A-Z a-z 0-9 _ - only allowed
                                       </small>
                                    </div>
                                 </div>
                                 <div class="col-sm-12 col-xs-12 col-md-6">
                                    <div class="form-group">
                                       <label for="branchnameinput">Branch name</label><span class="text-danger">*</span>
                                       <input type="text" class="form-control" name="branchnameinput" parsley-trigger="change" required="required" placeholder="Enter default branch name"  data-parsley-pattern="^[-\w_]{3,50}$">
                                       <small class="text-muted">A-Z a-z 0-9 _ - only allowed
                                       </small>
                                    </div>
                                 </div>
                                 <div class="col-sm-12 col-xs-12 col-md-12">
                                    <div class="form-group">
                                       <label for="descriptioninput">Project description</label>
                                       <input type="text" class="form-control" name="descriptioninput" parsley-trigger="change" placeholder="Enter project description"  data-parsley-pattern="^[-\w_ ]{0,250}$">
                                       <small class="text-muted">max 250 characters
                                       </small>
                                    </div>
                                 </div>
                                 <div class="col-sm-12 col-xs-12 col-md-12">
                                    <div class="form-group">
                                       <label for="commitmessageinput">Commit Message</label><span class="text-danger">*</span>
                                       <input type="text" class="form-control" name="commitmessageinput" parsley-trigger="change" required="required" placeholder="Enter commit message"  data-parsley-pattern="^[-\w_ ]{3,250}$">
                                       <small class="text-muted">max 250 characters
                                       </small>
                                    </div>
                                 </div>
                              </div>
                              <p class="text-muted mb-0 font-12">&nbsp</p>
                              <div class="row">
                                 <div class="col-sm-12 col-xs-12">
                                    <h4 class="header-title m-t-0">Add Files</h4>
                                    <div class="p-20">
                                       <div class="form-group clearfix">
                                          <div class="col-sm-12 padding-left-0 padding-right-0">
                                             <input type="file" name="files[]" id="filer_input1" parsley-trigger="change" required="required" data-parsley-required-message="Minimum one file required" multiple="multiple">
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <div class="form-group  m-b-0" style="margin-left: 30px;">
                                 <button class="btn btn-primary waves-effect waves-light" type="submit">
                                 Add Project
                                 </button>
                                 <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                                 Cancel
                                 </button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <footer class="footer text-right">
            2017 © VC-Chain.
         </footer>
      </div>
      <script>
         var resizefunc = [];
      </script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/tether.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/detect.js' %}"></script>
      <script src="{% static 'js/fastclick.js' %}"></script>
      <script src="{% static 'js/jquery.blockUI.js' %}"></script>
      <script src="{% static 'js/waves.js' %}"></script>
      <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
      <script src="{% static 'plugins/jquery.filer/js/jquery.filer.min.js' %}"></script>
      <script src="{% static 'plugins/parsleyjs/parsley.min.js' %}"></script>
      <script src="{% static 'js/jquery.app.js' %}"></script>
      <script src="{% static 'pages/jquery.fileuploads.init.js' %}"></script>
   </body>
</html>

vc_chain/templates/commits.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <title>VC-chain</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body class="fixed-left">
    <div id="wrapper">
    <div class="topbar">
      <div class="topbar-left">
        <a href="{% url 'index' %}" class="logo">
        <i class="fa fa-link"></i>
        <span>VC-chain</span>
        </a>
      </div>
      <nav class="navbar-custom">
        {% include "user_dropdown.html" %}
        <ul class="list-inline menu-left mb-0">
          <li class="float-left">
            <button class="button-menu-mobile open-left waves-light waves-effect">
            <i class="zmdi zmdi-menu"></i>
            </button>
          </li>
        </ul>
      </nav>
    </div>
    <div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
      {% include "sidebar_menu.html" %}
      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-12">
                <div class="page-title-box">
                  <h4 class="page-title float-left">{{ commits.project }}</h4>
                  <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">VC-Chain</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'dashboard' user.username %}">{{ user.username }}</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'projects-list' user.username %}">Projects</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'project-explorer' user.username commits.project %}">{{ commits.project }}</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'project-explorer' user.username commits.project commits.branch %}">{{ commits.branch }}</a></li>
                    <li class="breadcrumb-item active">commits</li>
                  </ol>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
            <div class="row">
              {% for commit_set in commits.commits_by_date %}
                <div class="col-sm-12">
                  <div class="card m-b-20">
                    <div class="card-header project-card-header font-15">
                      <i class="zmdi zmdi-time-restore font-16"></i><span class="margin-10">Commits on {{ commit_set.date }}</span>
                    </div>
                    {% for commit in commit_set.commits %}
                      <div class="card-block file-bottom-line">
                        <div class="row">
                          <div class="col-sm-10">
                            <div class="inline-box">
                              <img src="{{ MEDIA_URL }}{{ commit.author_img }}" alt="user" class="rounded-circle" style="width: 50px; height: 50px">
                              <div class="margin-20">
                                <div class="text-primary font-weight-bold font-16">{{ commit.message }}</div>
                                <div class="commit-time-info font-14"><a href="#" class="text-success font-weight-bold">{{ commit.author }}</a> committed on {{ commit_set.date }}</div>
                              </div>
                            </div>
                          </div>
                          <div class="col-sm-2">
                            <div class="pull-right m-t-15">
                              <button type="button" class="btn btn-outline-primary waves-effect waves-light margin-20 margin-t-5" onclick='location.href="{% url 'commit-diff' user.username commits.project commits.branch commit.id %}"'>View Commit</button>
                            </div>
                          </div>
                          <div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer text-right">
        2017 © VC-Chain.
      </footer>
    </div>
    <script>
      var resizefunc = [];
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/detect.js' %}"></script>
    <script src="{% static 'js/fastclick.js' %}"></script>
    <script src="{% static 'js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'js/waves.js' %}"></script>
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'js/jquery.app.js' %}"></script>
  </body>
</html>

vc_chain/templates/people.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <title>VC-chain</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body class="fixed-left">
    <div id="wrapper">
    <div class="topbar">
      <div class="topbar-left">
        <a href="{% url 'index' %}" class="logo">
        <i class="fa fa-link"></i>
        <span>VC-chain</span>
        </a>
      </div>
      <nav class="navbar-custom">
        {% include "user_dropdown.html" %}
        <ul class="list-inline menu-left mb-0">
          <li class="float-left">
            <button class="button-menu-mobile open-left waves-light waves-effect">
            <i class="zmdi zmdi-menu"></i>
            </button>
          </li>
        </ul>
      </nav>
    </div>
    <div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
      {% include "sidebar_menu.html" %}
      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-12">
                <div class="page-title-box">
                  <h4 class="page-title float-left">{{ type }}</h4>
                  <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">VC-Chain</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'dashboard' user.username %}">{{ user.username }}</a></li>
                    <li class="breadcrumb-item active">{{ type }}</li>
                  </ol>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
            <div class="row">
              {% for person in people %}
                <div class="col-xs-12 col-md-12 col-lg-12 col-xl-4">
                  <a href="{% url 'dashboard' person.username %}">
                    <div class="card-box widget-user">
                      <img src="{{ MEDIA_URL }}{{ person.img }}" class="img-responsive rounded-circle" alt="user">
                      <div class="wid-u-info margin-20 user-info-container">
                        <h5 class="m-t-20 m-b-5 inline black-link">{{ person.name }}</h5>
                        <span class="text-primary font-weight-bold margin-10">{{ person.username }}</span>
                        <p class="text-muted mb-0 font-13">{{ person.email }}</p>
                      </div>
                    </div>
                  </a>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <footer class="footer text-right">
        2017 © VC-Chain.
      </footer>
    </div>
    <script>
      var resizefunc = [];
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/detect.js' %}"></script>
    <script src="{% static 'js/fastclick.js' %}"></script>
    <script src="{% static 'js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'js/waves.js' %}"></script>
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'js/jquery.app.js' %}"></script>
  </body>
</html>